---
label: Project
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
  description: Name of the project lol
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Give an epic description of the project
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: A lil preview of the epic project
- name: code
  type: text
  config:
    required: false
  label: Code
  description: Link to the code of the project
- name: live
  type: text
  config:
    required: false
  label: Live
  description: Link to the live demo of the project
